Iter9
dmihailovStudy/opsmetricstore pull request #10
Opened 2024-05-13 04:02 UTC by dmihailovStudy

2024-05-13 08:03 UTC, gonozov0 commented on cmd/agent/main.go
> +const compressRequest = false
По дефолту по заданию true

2024-05-13 08:03 UTC, gonozov0 commented on cmd/server/main.go
> +	}
Стоит вынести в отдельную функцию, которая вернет структуру конфиг

2024-05-14 12:40 UTC, gonozov0 requested changes
Хорошая работа 👍
К сожалению прошлые итерации ревьюил не я, поэтому необходим серьезный рефакторинг архитектуры кода, конкретные вещи я описал отдельными комментариями
Я помню, что ты говорил про проблему с дедлайнами
Если нужно, я без проблем могу зачесть этот спринт (напиши и отправь на повторное ревью без исправлений если надо)
Но все моменты, что я описал, давай править в этом мр, чтобы не запутаться, только после этого по факту приступать к следующим итерациям
Если что-то непонятно по тем моментам, что описал (даже если это вопросы "а зачем?"), смело задавай их в чате и записывайся на 1:1

2024-05-14 12:40 UTC, gonozov0 commented on cmd/agent/main.go
>  	if envs.Address != "" {
main должна быть простая и понятная функция с минимальным количеством строк, вынеси все что касается получения енв и флагов в отдельное место

2024-05-14 12:40 UTC, gonozov0 commented on cmd/agent/main.go
>  			userStats.RandomValue = rand.Float64()
Это также уже бизнес логика вынеси все, что касается сбора метрик и их отправки в пакет agent в функцию Run

2024-05-14 12:40 UTC, gonozov0 commented on internal/logging/responseWritter.go
насколько я понимаю тут ты сделал обертку над gin.ResponseWriter для своего удобства
так как это можно применять и в других любых твоих проектах, то это следует положить в pkg/response_writer/

2024-05-14 12:40 UTC, gonozov0 commented on internal/config/agent/config.go
не совсем верно выстроил структуру проекта, на верхнем уровне должно быть понятное резделение на сервисы если они есть, чтобы другие люди могли легко погружаться в твой проект
Поэтому структура в internal у тебя должна быть такая:
- server
    - config
    - handlers
         - templates 
    - storages
- agent
     - config
     - collector (сборщик метрик)
     - sender (отправитель метрик)
- shared (общая логика и структуры, использующиеся и в agent и в server)
    - сюда как раз можно положить metrics.go

2024-05-14 12:40 UTC, gonozov0 commented on internal/storage/storage.go
> +func GetMetricValue(metricType, metricName string, storage *Storage) (bool, string, int64, float64, error) {
Про DI и необходимость интерфейса для Storage и отдельную реализацию этого интерфейса InMemoryStorage я тебе вроде все рассказал на 1:1, но на всякий продублирую ссылки на примеры из своего шаблона:
- [объявление интерфейса](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handler.go#L9)
- [InMemory реализация](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/infrastructure/users/in_memory.go)
- [Подкладывание InMemory реализации для тестов](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handlers_test/suite_test.go#L23)
- [Подкладывание нужной реализации для прода](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/server.go#L43)

2024-05-14 13:56 UTC, dmihailovStudy commented
Сделал несколько фиксов по вчерашнему ревью: сделал флаг компрессии true и вынес всю работу с флагами в пакет config. Все остальное обещаю исправить в следующем спринте

2024-05-15 13:39 UTC, dmihailovStudy commented
Займусь переделкой архитектуры в оставшиеся время, постараюсь максимально наверстать пропущенные спринты

2024-05-16 07:03 UTC, gonozov0 commented on internal/config/server/config.go
> +func (c *Config) Load() {
Нету смысла делать метод для конфига и ссылочный тип
Нужна просто функция инициализация конфига NewConfig или LoadConfig, которая будет его возвращать

2024-06-23 11:44 UTC, merged