Iter5
dmihailovStudy/opsmetricstore pull request #5
Opened 2024-02-15 19:24 UTC by dmihailovStudy

2024-02-16 21:47 UTC, valentinsoe requested changes
Спасибо за работу!
Здорово что написаны тесты и пишутся подробные логи. 

Чего бы хотелось поменять - больше структурировать код. Сейчас очень много глобальных переменных. И весь код за редким(и не всегда на мой взгляд очевидным) исключением написан в main.

Рекомендую оставить в main только инициализацию конфигурации и запуск "сервисов". А все остальное разложить по отдельным модулям:
1) модуль для работы с конфигурацией
2) модуль хранения метрик
3) модуль реализующий http хендлеры.

Еще мне не очень нравится подход с хранением значений метрик как строк. Для counter это постоянная их конвертация туда-сюда. Я бы предложил подумать над другим решением.

2024-02-16 21:47 UTC, valentinsoe commented on cmd/agent/main.go
> +	poolTicker := time.NewTicker(time.Duration(pollIntervalSec) * time.Second)
poolTicker все-таки pollTicker

2024-02-16 21:47 UTC, valentinsoe commented on cmd/agent/main.go
> +	flag.StringVar(&endpoint, aFlag, aDefault, aUsage)
Всю работу с конфигурацией, что флаги, что переменные окружения, лучше оформить во что-то отдельное.
В лучшем случае модуль, в худшем - отдельную функцию.

2024-02-16 21:47 UTC, valentinsoe commented on cmd/agent/main.go
> +	}
Если pollInterval = 2c, reportInterval = 10c. То чему будет равна метрика pollcount на сервере спустя 20с? (если считать что все операции моментальные и тикеры идеально точные)?

2024-02-16 21:47 UTC, valentinsoe commented on cmd/agent/main.go
> +	defer poolTicker.Stop()
reportTicker  тогда бы тоже стоило остановить

2024-02-16 21:47 UTC, valentinsoe commented on cmd/agent/main.go
> +		defer resp.Body.Close()
В таком случае использование defer - не самое удачное. Потому что все закрытия Body выполняться только по окончанию функции(а не итерации цикла).
Критично? - Нет. Но "неаккуратно"

2024-02-16 21:47 UTC, valentinsoe commented on cmd/server/main.go
> +	responseCode := CheckUpdateMetricCorrectness(url.Path)
Название функции начинается со слова Check - я бы не предполагал, что она может менять значение.

2024-02-16 21:47 UTC, valentinsoe commented on cmd/server/main.go
> +	url = url[1:] // Delete first "/" to escape metricData[0] = ""
У нас же URL параметризован в gin. Не стоит его парсить "руками"

2024-02-16 21:47 UTC, valentinsoe commented on cmd/server/main.go
> +	router.POST(updatePagePath, UpdatePage)
Опять замечание по именованию. Все кроме списка метрик сложно назвать "страницей", это методы API

2024-02-16 21:47 UTC, valentinsoe commented on internal/templates/html/metrics.go
> +	<body>{{.metrics}}</title>
Что-то с тэгами погло не так:) <head> не закрыт, <title> закрыт дважды

2024-02-16 21:47 UTC, valentinsoe commented on cmd/server/main.go
> +	c.HTML(http.StatusOK, "metrics", gin.H{
Если чуть дописать темплейт, то можно в него будет просто передать всю мапу, не склеивая ее предварительно в строки.

2024-02-16 21:47 UTC, valentinsoe commented on internal/metrics/types.go
> +	if metric == PollCountMetric {
Это очень негибкая схема.  Если на сервер прислать метрику типа counter с именем отличным от PollCount -> он будет считать ее gauge.

У нас есть требование, что агент отсылает такие метрики. Но что сервер корректно работает только с такими - нету.

2024-02-26 16:36 UTC, dmihailovStudy commented on internal/metrics/types.go
> +	if metric == PollCountMetric {
Не совсем понял, этой же функцией не пользуется сервер - только агент. У сервера нет вайтлистов имен метрик, т.е. если на сервер прислать метрику типа counter с именем отличным от PollCount он будет воспринимать ее как новую метрику типа counter (если значение соответствует int64)

2024-02-26 16:42 UTC, mikhailov-da commented on cmd/agent/main.go
> +	}
Если все операции моментальные и тикеры идеально точные:
- Мы начнем обновлять метрики на 20-й секунде
- Моментально отправятся самые актуальные метрики к 20-й секунде, то есть pollСount = 9

По заданию написано:
Обновлять метрики из пакета runtime с заданной частотой: pollInterval — 2 секунды
Отправлять метрики на сервер с заданной частотой: reportInterval — 10 секунд

То есть привязки отправки метрик после обновления нет. Поэтому не реализовывал отправку с проверкой по времени внутри тела pollTicker

2024-02-26 16:46 UTC, dmihailovStudy commented on cmd/agent/main.go
> +	poolTicker := time.NewTicker(time.Duration(pollIntervalSec) * time.Second)
Переименовал

2024-02-26 16:46 UTC, dmihailovStudy commented on cmd/agent/main.go
> +	flag.StringVar(&endpoint, aFlag, aDefault, aUsage)
Вынес все в config.go

2024-02-26 16:47 UTC, dmihailovStudy commented on cmd/agent/main.go
> +	defer poolTicker.Stop()
Добавил остановку reportTicker

2024-02-26 16:47 UTC, dmihailovStudy commented on cmd/agent/main.go
> +		defer resp.Body.Close()
Переместил

2024-02-26 16:47 UTC, dmihailovStudy commented on cmd/server/main.go
> +	url = url[1:] // Delete first "/" to escape metricData[0] = ""
Убрал ручной парсинг url

2024-02-26 16:47 UTC, dmihailovStudy commented on cmd/server/main.go
> +	router.POST(updatePagePath, UpdatePage)
Переименовал в middleware и handlers

2024-02-26 16:47 UTC, dmihailovStudy commented on internal/templates/html/metrics.go
> +	<body>{{.metrics}}</title>
Не заметил, исправил

2024-02-26 16:48 UTC, dmihailovStudy commented on cmd/server/main.go
> +	c.HTML(http.StatusOK, "metrics", gin.H{
Теперь передается вся мапа

2024-02-27 16:38 UTC, valentinsoe commented on cmd/agent/main.go
> +	}
На 10-й секунде отправится 4(или 5), на 20-й секунде 9(или 10). Какое значение метрики после этого будет на сервере?

2024-02-27 16:40 UTC, valentinsoe commented on internal/metrics/types.go
> +	if metric == PollCountMetric {
Ок, согласен. Сервер ей не пользуется.

2024-02-27 16:44 UTC, valentinsoe approved these changes
Спасибо за исправления!
Касательно метрики PollCount прочитай ответ в комментарии.

2024-02-27 16:50 UTC, dmihailovStudy commented on cmd/agent/main.go
> +	}
Если тикеры идеально точные, то то на сервере значение метрики будет:
- После 10 секунд отправим pollCount = 4: pollCount = 4 (Когда передаем в первый раз метрику, инициализируем ее отправленным значением) 
- После 20 секунд pollCount = 9: pollCount = 4 + 9 = 13

В текущей ситуации по логам времени видно, что тикеры обрабатываются не идеально точно, по трассировке реального кода:
- После 10 секунд отправим pollCount = 5: pollCount = 5 (Когда передаем в первый раз метрику, инициализируем ее отправленным значением) 
- После 20 секунд pollCount = 10: pollCount = 5 + 10 = 15

По логике получается что эту метрику надо просто инкрементить на 1, так как в текущем виде на сервере она не отражает реальное число обновлений. Но насколько следует из задания надо было реализовать ее именно так

2024-02-27 17:04 UTC, valentinsoe commented on cmd/agent/main.go
> +	}
По логике надо успешно отправленный счетчик на агента обнулять:)

2024-02-27 17:26 UTC, dmihailovStudy commented on cmd/agent/main.go
> +	}
Хорошо, это поправлю - звучит логично. Я сейчас пересмотрел задание второго инкремента, и там этого требования нет, написано только:

> К метрикам пакета runtime добавьте ещё две:
PollCount (тип counter) — счётчик, увеличивающийся на 1 при каждом обновлении метрики из пакета runtime (на каждый pollInterval — см. ниже)
.....
По умолчанию приложение должно:
Обновлять метрики из пакета runtime с заданной частотой: pollInterval — 2 секунды

Поэтому сразу не догадался, что надо так это реализовать

2024-02-28 11:37 UTC, merged